apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: drone-detector-api
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/container-dependencies: '{"collector":["app"]}'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - name: app
        image: europe-north2-docker.pkg.dev/drone-detection-mlops/ml-containers/api:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
        env:
        - name: MODE
          value: cloud
      - name: collector
        image: us-docker.pkg.dev/cloud-ops-agents-artifacts/cloud-run-gmp-sidecar/cloud-run-gmp-sidecar:1.2.0
  traffic:
  - percent: 100
    latestRevision: true
